### ISSUE TITLE
The VM link is missing

### ISSUE THREAD

**Issue by jwkim90** [mscastanho/bpf-tutorial#1]
Hello, many thanks for giving the valuable code and guide for eBPF/XDP tutorial. :)

While reading the survey paper, I've tried to reproduce the examples with the VM,
but I think its link is missing now.

Could you please restore it or give it to me?

Thanks.
Regard,
Jinwoo

**Comment by mscastanho** [comment]
Hi Jinwoo, I already notified the website admin. The file probably got moved around in a recent change. Hopefully it will be back soon.

**Comment by jwkim90** [comment]
Got it. I hope it will be soon available. Thanks a lot!

**Comment by mscastanho** [comment]
@jwkim90 unfortunately the VM is lost 😢 .
However, you should be able get instructions on how to setup a similar environment from  [the xdp-project/xdp-tutorial repository](https://github.com/xdp-project/xdp-tutorial).

Note that BPF has a fast pace of development, so using the latest version of kernel / clang / elfutils / libbpf and related tools is best to have access to all features. You'll be better served by using a newer distro than what our VM provided anyways.

Hope this helps =)

**Comment by jwkim90** [comment]
@mscastanho I see. Thanks for letting me know it! :)
